version: '3.8'

services:
  app:
    build: ./src
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "your_strong_password"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:

  